Better fix for #753
beanshell/beanshell pull request #756
Opened 2024-01-08 15:00 UTC by opeongo

- All comments are special tokens
- remove BSHFormalComment and add accessor methods to Parser
- add and modify tests
- adjust bshdoc.bsh to use accessor methods

2024-03-21 11:59 UTC, nickl- requested changes
Looks like there is still debugging code in here, and not sure what the reason is for changing the Token to a Node, this must surely have a performance knock.

2024-03-21 11:59 UTC, nickl- commented on scripts/bshdoc.bsh
> +System.err.println("filenames="+Arrays.toString(filenames));
Is this just for debugging?

2024-03-21 11:59 UTC, nickl- commented on scripts/bshdoc.bsh
> +System.err.println("list="+Arrays.toString(list));
Same as previous instance of `System.err.println`

2024-03-21 11:59 UTC, nickl- commented on src/main/jjtree/bsh.jjt
> -void FormalComment() #FormalComment( retainComments ) :
Ok so we are turning FormalComment into a Node and not a Token anymore.

Not sure I follow the reasoning here, please explain.

2024-03-21 12:10 UTC, nickl- commented on src/main/jjtree/bsh.jjt
> -void FormalComment() #FormalComment( retainComments ) :
My bad

2024-03-21 12:12 UTC, nickl- commented
Looks good, just check on the debugging code.

2024-08-10 14:17 UTC, nickl- commented
Still waiting on review fixes

2024-08-10 20:27 UTC, opeongo commented
Updated now for review comments

2026-09-17 20:23 UTC, jimjag commented
Concept is OK but we've diverged enough that any implementation would require some rework. Closing this PR and recommending a new one if this is still something to be considered with a new patch.

2026-09-17 20:23 UTC, closed without merging